name: multi_image_picker
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 3.0.22
author: Radoslav Vitanov <radoslav.vitanov@icloud.com>
homepage: https://github.com/Sh1d0w/multi_image_picker

dependencies:
  http : any
  path : any
  image : any
  shared_preferences : any
  curved_navigation_bar: ^0.1.24
  flutter:
    sdk: flutter
  meta: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  assets :
    - assets/

  plugin:
    androidPackage: com.vitanov.multiimagepicker
    pluginClass: MultiImagePickerPlugin
environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"
    flutter: ">=0.1.4 <2.0.0"

